parameters:
    database_driver:   pdo_sqlite
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: ~
    database_path:     %kernel.root_dir%/sflive2013.db

    database_test_driver:   pdo_sqlite
    database_test_host:     127.0.0.1
    database_test_port:     ~
    database_test_name:     symfony
    database_test_user:     root
    database_test_password: ~
    database_test_memory:   ~
    database_test_path:     %kernel.root_dir%/sflive2013_test.db

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
